# Generated by Django 4.0.3 on 2022-04-06 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_remove_halfmeterpizza_dough_custompizza_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('cellphone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('is_delivery', models.BooleanField(default=True)),
                ('is_far', models.BooleanField(default=False)),
                ('order_date_time', models.DateTimeField()),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('notes', models.CharField(max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('beverages', models.ManyToManyField(to='menu.beverage')),
                ('custom_pizzas', models.ManyToManyField(to='menu.custompizza')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.customer')),
                ('half_meter_pizzas', models.ManyToManyField(to='menu.halfmeterpizza')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('starts', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.status'),
        ),
    ]
