# Generated by Django 4.0.3 on 2022-04-06 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_name',
            new_name='username',
        ),
    ]
