# Generated by Django 4.0.3 on 2022-04-11 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_user_address_alter_user_cellphone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
