# Generated by Django 4.0.3 on 2022-04-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_rename_user_name_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='starts',
            new_name='stars',
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Titolo', max_length=100),
            preserve_default=False,
        ),
    ]
