# Generated by Django 4.0.3 on 2022-04-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_rename_user_id_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
