# Generated by Django 4.0.3 on 2022-04-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_rename_starts_review_stars_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
