# Generated by Django 4.0.3 on 2022-04-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_custompizza_notes_alter_halfmeterpizza_notes'),
        ('operations', '0004_alter_order_order_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='beverages',
            field=models.ManyToManyField(null=True, to='menu.beverage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_pizzas',
            field=models.ManyToManyField(null=True, to='menu.custompizza'),
        ),
        migrations.AlterField(
            model_name='order',
            name='half_meter_pizzas',
            field=models.ManyToManyField(null=True, to='menu.halfmeterpizza'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
