# Generated by Django 4.0.3 on 2022-04-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_remove_customer_first_name_remove_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
