# Generated by Django 4.0.3 on 2022-04-12 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_order_beverages_alter_order_custom_pizzas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.order'),
        ),
    ]
