# Generated by Django 4.0.3 on 2022-04-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='email_address',
        ),
    ]
