# Generated by Django 4.0.3 on 2022-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_rename_email_customer_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.CharField(max_length=50),
        ),
    ]
