# Generated by Django 4.0.3 on 2022-04-09 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.CharField(max_length=20)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('is_beer', models.BooleanField(default=False)),
                ('is_alcoholic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_thick', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Dough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_in_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('is_lactose_free', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='MenuPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredients', models.ManyToManyField(to='menu.ingredient')),
                ('pizza_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pizzatype')),
            ],
        ),
        migrations.CreateModel(
            name='HalfMeterPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('custom_pizza_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_pizza_1', to='menu.custompizza')),
                ('custom_pizza_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_pizza_2', to='menu.custompizza')),
                ('custom_pizza_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_pizza_3', to='menu.custompizza')),
            ],
        ),
        migrations.AddField(
            model_name='custompizza',
            name='added_ingredients',
            field=models.ManyToManyField(to='menu.ingredient'),
        ),
        migrations.AddField(
            model_name='custompizza',
            name='dough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dough'),
        ),
        migrations.AddField(
            model_name='custompizza',
            name='menu_pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menupizza'),
        ),
        migrations.AddField(
            model_name='custompizza',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.size'),
        ),
    ]
