# Generated by Django 4.0.3 on 2022-04-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halfmeterpizza',
            name='dough',
        ),
        migrations.AddField(
            model_name='custompizza',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='halfmeterpizza',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
    ]
