# Generated by Django 4.0.3 on 2022-04-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompizza',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='halfmeterpizza',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
